#charon:
#  mappings:
#    -
#        name: sample mapping
#        path: /figis
#        destinations: http://hqlprfigis1/figis/
#  metrics:
#          enabled: true
#  tracing:
#        enabled: true

# Proxy configuration
zuul:
  routes:
    config:
      path: /figis/qrcode/**
      url: http://www.fao.org/figis/qrcode/**

ribbon:
  eureka:
    enabled: false
